user:
  name:
    length: 50
  email:
    length: 255
  password:
    length: 6
  per_page: 20
  index:
    size: 50
  reset:
    password: 2

user_helper:
  size: 80

session:
  remember: 1

entry:
  title:
    length: 140
  per_page: 20
  avatar:
    size: 60

show_follow:
  size: 40
